# Generated by Django 3.2.8 on 2021-10-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211027_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=128, max_length=999),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=128, max_length=999),
        ),
    ]
