# Generated by Django 3.2.8 on 2021-10-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20211027_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convertedimage',
            name='child',
        ),
        migrations.AddField(
            model_name='convertedimage',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='images.image'),
        ),
    ]
