# Generated by Django 3.2.8 on 2021-10-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20211027_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedimage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='images.image'),
        ),
    ]
